# Project information
site_name: 'Pentesting'
site_description: 'A bunch of miscellaneous pentesting and scripting notes'
site_author: 'Glasgow'
#site_url: ''

# Repository
repo_name: 'GlasgOWned/PenTesting'
repo_url: 'https://github.com/GlasgOWned/PenTesting'


# Configuration
theme:
  name: 'material'
  language: 'en'
  palette:
    primary: 'indigo'
    accent: 'indigo'
  font:
    text: 'Roboto'
    code: 'Roboto Mono'

# Extensions
markdown_extensions:
    - admonition
    - codehilite:
        guess_lang: false
    - toc:
        permalink: true
    - meta
    - pymdownx.details
    - pymdownx.inlinehilite
    - pymdownx.magiclink
    - pymdownx.mark
    #- pymdownx.superfences
    - pymdownx.tabbed
    - pymdownx.tasklist:
        custom_checkbox: true
    - pymdownx.tilde

docs_dir: notes
site_dir: site
